<?php
/**
 * Created by dhailing
 * User: dhailing
 * Email: test@test.com
 * Date: 2020/12/17 0017
 * Time: 20:39
 */

namespace ninenight\Send\Gateways\FlyingPigeon;


class ActionGateway extends FlyingPigeon
{
    /**
     * 发送短信
     * @param array $config_biz
     * @return mixed
     * User: DH
     * Email: 206989662@qq.com
     * Date: 2019/7/17
     * Time: 15:53
     */
    public function send(array $config_biz)
    {
        parent::send($config_biz); // TODO: Change the autogenerated stub

        return $this->doSend();
    }
}
