<?php
/**
 * 短信群发
 * Created by Dh106
 * User: DH
 * Email: 206989662@qq.com
 * Date: 2019/8/30
 * Time: 10:57
 */

namespace dhsms\Send\Gateways\Tencent;


class MultiGateway extends Tencent
{
    public function send(array $config_biz)
    {
        $config_biz['url'] = 'https://yun.tim.qq.com/v5/tlssmssvr/sendmultisms2';
        $config_biz['gateway'] = 'Multi';
        parent::send($config_biz); // TODO: Change the autogenerated stub
        return $this->doSend();
    }
}
