<?php
/**
 * 语音通知短信
 * Created by Dh106
 * User: DH
 * Email: 206989662@qq.com
 * Date: 2019/8/30
 * Time: 11:03
 */

namespace dhsms\Send\Gateways\Tencent;


class VoicePromptGateway extends Tencent
{
    public function send(array $config_biz)
    {
        $config_biz['url'] = 'https://yun.tim.qq.com/v5/tlsvoicesvr/sendvoiceprompt';
        $config_biz['gateway'] = 'VoicePrompt';
        parent::send($config_biz); // TODO: Change the autogenerated stub
        $this->doSend();
    }
}
