<?php
/**
 * Created by Dh106
 * User: DH
 * Email: 206989662@qq.com
 * Date: 2019/7/17
 * Time: 15:00
 */

namespace ninenight\Send\Gateways\Xuanwu;


class ActionGateway extends Xuanwu
{

    /**
     * 发送
     * @param array $config_biz
     * @return mixed
     * User: DH
     * Email: 206989662@qq.com
     * Date: 2019/7/17
     * Time: 15:53
     */
    public function send(array $config_biz)
    {
        parent::send($config_biz); // TODO: Change the autogenerated stub

        return $this->doSend();
    }
}
